language: go
go:
  - 1.4
sudo: true
before_install:
  - sudo apt-add-repository universe
  - sudo apt-get install -y gearman-job-server
# When travis whitelists package:
# addons:
#   apt:
#     packages:
#       - gearman-job-server
